services:
  leilao-db:
    image: postgres:16-alpine
    container_name: leilao-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: leilao
      POSTGRES_PASSWORD: leilao
      POSTGRES_DB: leilao
    ports:
      - "5433:5432"
    volumes:
      - leilao-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U leilao"]
      interval: 5s
      timeout: 3s
      retries: 20

  leilao-redis:
    image: redis:7-alpine
    container_name: leilao-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  leilao-pgdata:
