import { chromium } from 'playwright-core';
const url = process.argv[2] ?? 'http://localhost:4500/';
const out = process.argv[3] ?? '/tmp/leilao-shots/home.png';
const width = Number(process.argv[4] ?? 1440);
const browser = await chromium.launch({ headless: true, executablePath: '/home/gustavopereira/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome' });
const page = await browser.newPage({ viewport: { width, height: 1000 } });
const errors = [];
page.on('console', (m) => m.type() === 'error' && errors.push(`console: ${m.text()}`));
page.on('pageerror', (e) => errors.push(`pageerror: ${e.message}`));
page.on('requestfailed', (r) => errors.push(`requestfailed: ${r.url().slice(0, 90)} ${r.failure()?.errorText}`));
page.on('response', (r) => r.status() >= 400 && r.url().includes('localhost') && errors.push(`http ${r.status()}: ${r.url()}`));
await page.goto(url, { waitUntil: 'networkidle', timeout: 30000 });
await page.waitForTimeout(1500);
await page.screenshot({ path: out, fullPage: false });
console.log('total exibido:', await page.locator('#total').textContent());
console.log('cards:', await page.locator('.card').count());
console.log('interpretado:', (await page.locator('#interpreted').textContent())?.trim() || '(vazio)');
console.log('ws:', (await page.locator('#wsdot').getAttribute('class')));
console.log(errors.length ? 'PROBLEMAS:\n - ' + errors.join('\n - ') : 'sem erros de console/rede');
await browser.close();
